#*****************************************************************************#
#    Copyright (C) 2022 Julian Xhokaxhiu                                      #
#                                                                             #
#    This file is part of MMNx                                                #
#                                                                             #
#    MMNx is free software: you can redistribute it and/or modify             #
#    it under the terms of the GNU General Public License as published by     #
#    the Free Software Foundation, either version 3 of the License            #
#                                                                             #
#    MMNx is distributed in the hope that it will be useful,                  #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of           #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
#    GNU General Public License for more details.                             #
#*****************************************************************************#

# Azure Pipeline YAML file

name: 0.0.1$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - '*'

pr:
  drafts: false

variables:
  _IS_BUILD_CANARY: false
  _RELEASE_NAME: MMNx
  _RELEASE_VERSION: v0
  _RELEASE_CONFIGURATION: Release
  _BUILD_VERSION: $(Build.BuildNumber)
  _BUILD_BRANCH: $(Build.SourceBranch)
  _CHANGELOG_VERSION: "0"
  # VCPKG: Enable Binary Caching
  VCPKG_BINARY_SOURCES: clear;nuget,https://pkgs.dev.azure.com/julianxhokaxhiu/Github/_packaging/MMNx/nuget/v3/index.json,readwrite
  # GIT: Fix reporting from stderr to stdout
  GIT_REDIRECT_STDERR: 2>&1

pool:
  vmImage: 'windows-2022'

jobs:
- job: MMNx
  timeoutInMinutes: 1440
  steps:
  - task: NuGetAuthenticate@0
  - task: PowerShell@2
    displayName: 'Build $(_RELEASE_NAME)'
    inputs:
      filePath: .ci\build.ps1
      failOnStderr: true
      pwsh: true
  - task: GitHubRelease@0
    condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')), succeeded())
    displayName: 'Delete $(_RELEASE_NAME) (Canary)'
    continueOnError: true
    inputs:
      gitHubConnection: github_ci
      action: delete
      tagSource: manual
      tag: canary
  - task: GitHubRelease@0
    condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')), succeeded())
    displayName: 'Create $(_RELEASE_NAME) (Canary)'
    inputs:
      gitHubConnection: github_ci
      assets: .dist\*.zip
      isPreRelease: true
      tagSource: manual
      tag: canary
      title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
      releaseNotesSource: input
      releaseNotes: |
        See https://github.com/julianxhokaxhiu/MMNx/blob/master/Changelog.md#next

        This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
  - task: GitHubRelease@0
    condition: and(eq(variables._IS_BUILD_CANARY, 'false'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')), succeeded())
    displayName: 'Create $(_RELEASE_NAME) (Stable)'
    inputs:
      gitHubConnection: github_ci
      assets: .dist\*.zip
      title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
      releaseNotesSource: input
      releaseNotes: |
        See https://github.com/julianxhokaxhiu/MMNx/blob/master/Changelog.md#$(_CHANGELOG_VERSION)
